default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: alejandrobravo09
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: users_crud_development

test:
  <<: *default
  database: users_crud_test

production:
  <<: *default
  database: users_crud_production
